# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calculator_pb2 as calculator__pb2

GRPC_GENERATED_VERSION = '1.65.5'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in calculator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class CalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/Calculator/Add',
                request_serializer=calculator__pb2.CalcRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalcResponse.FromString,
                _registered_method=True)
        self.Subtract = channel.unary_unary(
                '/Calculator/Subtract',
                request_serializer=calculator__pb2.CalcRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalcResponse.FromString,
                _registered_method=True)
        self.Multiply = channel.unary_unary(
                '/Calculator/Multiply',
                request_serializer=calculator__pb2.CalcRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalcResponse.FromString,
                _registered_method=True)
        self.Divide = channel.unary_unary(
                '/Calculator/Divide',
                request_serializer=calculator__pb2.CalcRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalcResponse.FromString,
                _registered_method=True)
        self.Modulus = channel.unary_unary(
                '/Calculator/Modulus',
                request_serializer=calculator__pb2.CalcRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalcResponse.FromString,
                _registered_method=True)
        self.Power = channel.unary_unary(
                '/Calculator/Power',
                request_serializer=calculator__pb2.CalcRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalcResponse.FromString,
                _registered_method=True)
        self.SquareRoot = channel.unary_unary(
                '/Calculator/SquareRoot',
                request_serializer=calculator__pb2.SingleRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalcResponse.FromString,
                _registered_method=True)
        self.Log = channel.unary_unary(
                '/Calculator/Log',
                request_serializer=calculator__pb2.SingleRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalcResponse.FromString,
                _registered_method=True)
        self.Sin = channel.unary_unary(
                '/Calculator/Sin',
                request_serializer=calculator__pb2.SingleRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalcResponse.FromString,
                _registered_method=True)
        self.Cos = channel.unary_unary(
                '/Calculator/Cos',
                request_serializer=calculator__pb2.SingleRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalcResponse.FromString,
                _registered_method=True)


class CalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subtract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Divide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Modulus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Power(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SquareRoot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Log(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=calculator__pb2.CalcRequest.FromString,
                    response_serializer=calculator__pb2.CalcResponse.SerializeToString,
            ),
            'Subtract': grpc.unary_unary_rpc_method_handler(
                    servicer.Subtract,
                    request_deserializer=calculator__pb2.CalcRequest.FromString,
                    response_serializer=calculator__pb2.CalcResponse.SerializeToString,
            ),
            'Multiply': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiply,
                    request_deserializer=calculator__pb2.CalcRequest.FromString,
                    response_serializer=calculator__pb2.CalcResponse.SerializeToString,
            ),
            'Divide': grpc.unary_unary_rpc_method_handler(
                    servicer.Divide,
                    request_deserializer=calculator__pb2.CalcRequest.FromString,
                    response_serializer=calculator__pb2.CalcResponse.SerializeToString,
            ),
            'Modulus': grpc.unary_unary_rpc_method_handler(
                    servicer.Modulus,
                    request_deserializer=calculator__pb2.CalcRequest.FromString,
                    response_serializer=calculator__pb2.CalcResponse.SerializeToString,
            ),
            'Power': grpc.unary_unary_rpc_method_handler(
                    servicer.Power,
                    request_deserializer=calculator__pb2.CalcRequest.FromString,
                    response_serializer=calculator__pb2.CalcResponse.SerializeToString,
            ),
            'SquareRoot': grpc.unary_unary_rpc_method_handler(
                    servicer.SquareRoot,
                    request_deserializer=calculator__pb2.SingleRequest.FromString,
                    response_serializer=calculator__pb2.CalcResponse.SerializeToString,
            ),
            'Log': grpc.unary_unary_rpc_method_handler(
                    servicer.Log,
                    request_deserializer=calculator__pb2.SingleRequest.FromString,
                    response_serializer=calculator__pb2.CalcResponse.SerializeToString,
            ),
            'Sin': grpc.unary_unary_rpc_method_handler(
                    servicer.Sin,
                    request_deserializer=calculator__pb2.SingleRequest.FromString,
                    response_serializer=calculator__pb2.CalcResponse.SerializeToString,
            ),
            'Cos': grpc.unary_unary_rpc_method_handler(
                    servicer.Cos,
                    request_deserializer=calculator__pb2.SingleRequest.FromString,
                    response_serializer=calculator__pb2.CalcResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Calculator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calculator/Add',
            calculator__pb2.CalcRequest.SerializeToString,
            calculator__pb2.CalcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subtract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calculator/Subtract',
            calculator__pb2.CalcRequest.SerializeToString,
            calculator__pb2.CalcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Multiply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calculator/Multiply',
            calculator__pb2.CalcRequest.SerializeToString,
            calculator__pb2.CalcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Divide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calculator/Divide',
            calculator__pb2.CalcRequest.SerializeToString,
            calculator__pb2.CalcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Modulus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calculator/Modulus',
            calculator__pb2.CalcRequest.SerializeToString,
            calculator__pb2.CalcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Power(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calculator/Power',
            calculator__pb2.CalcRequest.SerializeToString,
            calculator__pb2.CalcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SquareRoot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calculator/SquareRoot',
            calculator__pb2.SingleRequest.SerializeToString,
            calculator__pb2.CalcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Log(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calculator/Log',
            calculator__pb2.SingleRequest.SerializeToString,
            calculator__pb2.CalcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calculator/Sin',
            calculator__pb2.SingleRequest.SerializeToString,
            calculator__pb2.CalcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calculator/Cos',
            calculator__pb2.SingleRequest.SerializeToString,
            calculator__pb2.CalcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
