# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"/\n\x0b\x43\x61lcRequest\x12\x0f\n\x07number1\x18\x01 \x01(\x01\x12\x0f\n\x07number2\x18\x02 \x01(\x01\"\x1f\n\rSingleRequest\x12\x0e\n\x06number\x18\x01 \x01(\x01\"\x1e\n\x0c\x43\x61lcResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32\x96\x03\n\nCalculator\x12\"\n\x03\x41\x64\x64\x12\x0c.CalcRequest\x1a\r.CalcResponse\x12\'\n\x08Subtract\x12\x0c.CalcRequest\x1a\r.CalcResponse\x12\'\n\x08Multiply\x12\x0c.CalcRequest\x1a\r.CalcResponse\x12%\n\x06\x44ivide\x12\x0c.CalcRequest\x1a\r.CalcResponse\x12&\n\x07Modulus\x12\x0c.CalcRequest\x1a\r.CalcResponse\x12$\n\x05Power\x12\x0c.CalcRequest\x1a\r.CalcResponse\x12+\n\nSquareRoot\x12\x0e.SingleRequest\x1a\r.CalcResponse\x12$\n\x03Log\x12\x0e.SingleRequest\x1a\r.CalcResponse\x12$\n\x03Sin\x12\x0e.SingleRequest\x1a\r.CalcResponse\x12$\n\x03\x43os\x12\x0e.SingleRequest\x1a\r.CalcResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALCREQUEST']._serialized_start=20
  _globals['_CALCREQUEST']._serialized_end=67
  _globals['_SINGLEREQUEST']._serialized_start=69
  _globals['_SINGLEREQUEST']._serialized_end=100
  _globals['_CALCRESPONSE']._serialized_start=102
  _globals['_CALCRESPONSE']._serialized_end=132
  _globals['_CALCULATOR']._serialized_start=135
  _globals['_CALCULATOR']._serialized_end=541
# @@protoc_insertion_point(module_scope)
